### ISSUE TITLE
Video conference not working in iFrame on ios

### ISSUE THREAD

**Issue by bimal72** [OpenVidu/openvidu.io-docs#11]
Hello,

I have kept video server url in ionic app, within iFrame.
On android, it is working fine, but on ios, it does not open webcam and even not displaying video streaming of other party.

**Comment by micaelgallego** [comment]
Support in iOS is using ios-rtc cordova plugin (https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc). This plugin can have limitations like you are mentioning.
