### ISSUE TITLE
Stop Recording endpoint doc must specify session, not recording id

### ISSUE THREAD

**Issue by hmassad** [OpenVidu/openvidu.io-docs#21]
Reading the documentation for recording, in the section https://docs.openvidu.io/en/2.12.0/reference-docs/REST-API/#post-apirecordingsstart
for the method **POST /api/recordings/stop/<RECORDING_ID>**
please change **RECORDING_ID** for **SESSION_ID**
Thank you

**Comment by pabloFuente** [comment]
Docs are fine. You must provide the recordingId. But take into account that the recoridng id can be the same as the session if. Only if you start a second recording of the same session after stopping the previous one you will get a different recording id.
