### ISSUE TITLE
Let's Encrypt mislead

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [OpenVidu/openvidu.io-docs#23]
Hi there!

At https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/#1-prerequisites there's this statement:

> You don't need a valid SSL certificate as one can be automatically created for you by Let's Encrypt during the installation process.

Reading this looks like (IMO) Let's Encrypt creates invalid SSL, because the sentence starts with `You don't need a valid SSL` and ends with `created for you by Let's Encrypt`.

**Comment by micaelgallego** [comment]
Improved in https://github.com/OpenVidu/openvidu.io-docs/commit/d4e81e37ad0bb170100441ea8c43f36e78fa7972 and https://github.com/OpenVidu/openvidu.io-docs/commit/4f92e9c12d6f1e2df96560835de1a1abae82a3be
