### ISSUE TITLE
Docker compose insecure network rules

### ISSUE THREAD

**Issue by jdgarcia1381** [OpenVidu/openvidu.io-docs#26]
Hi,

Thanks for giving us a set of docker containers to deploy OpenVidu on production, those have been really useful. Right now we are using a DigitalOcean droplet (Ubuntu 20.04) to deploy the containers, following this documentation: https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises.

We want to report that the network rules used on the docker-compose file make those ports available for everyone, so you have to be careful. After enabling UFW (firewall) with ports 80 and 443 open, we had some problems trying to make those services available. Following this comment we solved the problem:
https://github.com/moby/moby/issues/4737#issuecomment-419705925

**Comment by micaelgallego** [comment]
Thank you for reporting the issue and pointing to a solution.

As you have the experience configuring UFW for a OpenVidu deployment, can you please clarify what exact steps have you done to protect OpenVidu instance? The comment you link is a bit complex to understand without the context you have.

Thank you for the help.

**Comment by jdgarcia1381** [comment]
We were doing some testing and decided to roll back that 'fix' because it was not working as expected.

Finally, what we did was to enable UFW and allow the list of ports described on [Openvidu Prerequisites](https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/#1-prerequisites) section:
```
ufw allow OpenSSH
ufw enable
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 3478/tcp
ufw allow 3478/udp
ufw allow 40000:57000/tcp
ufw allow 40000:57000/udp
ufw allow 57001:65535/tcp
ufw allow 57001:65535/udp
```

Maybe you should add a **warning to enable ufw** or some other firewall to prevent someone from accessing Redis or other services that are exposed on Docker by default.

**Comment by micaelgallego** [comment]
Thanks!
