### ISSUE TITLE
Suggest a way to set KMS_TURN_URL config like in 2.12.0 version

### ISSUE THREAD

**Issue by vinit14695** [OpenVidu/openvidu.io-docs#29]
How can i set turn server url in 2.13 and 2.14 ?

The [documentation ](https://docs.openvidu.io/en/2.12.0/reference-docs/openvidu-server-params/)of 2.12 states how to set this.

but 2.13 I couldn't find it in documentation.
Is there another way or is this deprecated?

**Comment by pabloFuente** [comment]
That only applied to the development container. With the current OpenVidu deployments this property makes no sense anymore.

Why would you want to give it a value?

**Comment by vinit14695** [comment]
Currently I am trying to setup a openVidu CE on my pc

I had successfully ran this image: openvidu/openvidu-server-kms:2.12.0 with my own turn server.

Now I want to try the upgraded docker image with my own turn server
is it not possible?

**Comment by pabloFuente** [comment]
So you want to "deploy" the openvidu development container for "production" in your own PC inside your LAN network?

**Comment by vinit14695** [comment]
Lets start again:
I already have an existing turn server. Will I be able to use this in the docker image of openvidu/openvidu-server-kms:2.14.0?

**Comment by pabloFuente** [comment]
I know all you want is a straight answer, but I want to understand why you would want to do that. Becauseopenvidu-server-kms docker container is NOT intended to be used in any way that would require to set the deprecated property KMS_TURN_URL. When I understand the reason, I may be able to help you by telling you how to do it or an alternative way to set the configuration you want inside the internal KMS running in the container.

But again, that Docker image is only intended for testing and development environments inside the same LAN network. So, no TURN, no public IP, no certificate should be configured and used when using openvidu-server-kms

Regards

**Comment by vinit14695** [comment]
Thanks for explaining. Can you tell me an ideal way to deploy for production? I'll delete this issue as it's my fault . Can we have a chat if you don't mind? I have a few questions I would like to ask you. It would be a great help for me.

**Comment by pabloFuente** [comment]
Sure. Follow Deploying OpenVidu for production instructions: https://docs.openvidu.io/en/2.14.0/deployment/

Since release 2.13.0, it is also based on Docker.
