### ISSUE TITLE
Missing link/doc for Deploy OpenVidu based Applications

### ISSUE THREAD

**Issue by nikhilakki** [OpenVidu/openvidu.io-docs#30]
Hello,

I'm trying to dockerize/package a Custom OpenVidu app by following docs for Production Deployment. On following the docs from the deployment section -
![Screenshot 2020-05-30 at 20 58 09](https://user-images.githubusercontent.com/17634231/83332364-78a54280-a2b8-11ea-94eb-afeb2d39c344.png)

For more information on how to disable it and deploy your own application (if needed) visit the section **[Deploy OpenVidu based Applications.](https://docs.openvidu.io/deployment/#deploy-openvidu-based-applications)** <- This link seems to be broken, screenshot -

![Screenshot 2020-05-30 at 20 56 25](https://user-images.githubusercontent.com/17634231/83332306-0c2a4380-a2b8-11ea-921e-faec58c4fc24.png)

If someone can point me to this part of the doc it will be very helpful, thank you.

**Comment by micaelgallego** [comment]
Thank you for reporting.

The broken link is now fixed
