### ISSUE TITLE
Missing document for RPC prepareReceiveVideoFrom

### ISSUE THREAD

**Issue by dofmind** [OpenVidu/openvidu.io-docs#47]
New RPC prepareReceiveVideoFrom was added on v2.18.0 but there is no document about RPC prepareReceiveVideoFrom.

**Comment by pabloFuente** [comment]
Not necessary yet. openvidu-android tutorial is already updated to work without this method

**Comment by dofmind** [comment]
> Not necessary yet. openvidu-android tutorial is already updated to work without this method

Why unnecessary? openvidu-android is just  a example. The document is more important. User can get wrong information from the missing document.

**Comment by micaelgallego** [comment]
This method is implemented in the server but currently is not used in OpenVidu CE neither OpenVidu PRO. 

This RPC method will be used in future releases and then it will be properly documented.

**Comment by pabloFuente** [comment]
Because the method that was added is still a feature in development. Part of the master branch, but not part of an official release.

**Comment by dofmind** [comment]
OK, i hope it's completed soon.
