### ISSUE TITLE
Confusing documentation on ionic-capacitor for iOS

### ISSUE THREAD

**Issue by ilbonte** [OpenVidu/openvidu.io-docs#53]
In this section: https://github.com/OpenVidu/openvidu.io-docs/blob/master/docs/tutorials/openvidu-ionic.md#configuration-requirements the documentation says to add an "adapter-4.0.1.js" file, but [on the example](https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-ionic-capacitor/src/app/app.component.ts#L55) this file is not used.
(Also I found a commit that removed the code regarding this file, but now I can not find it anymore.)

**Comment by ilbonte** [comment]
Found the commit: https://github.com/OpenVidu/openvidu-tutorials/commit/d6fbf4b5ca01d5c36b7b8e11025868d91b2845c3

It was on the example with cordova, not capacitor... but the portion of code is the same

**Comment by ilbonte** [comment]
I've spoken more deeply about the issues that I'm facing here: https://openvidu.discourse.group/t/issues-with-ios-and-openvidu-ionic-capacitor/4014

**Comment by ilbonte** [comment]
> Found the commit: [OpenVidu/openvidu-tutorials@d6fbf4b](https://github.com/OpenVidu/openvidu-tutorials/commit/d6fbf4b5ca01d5c36b7b8e11025868d91b2845c3)
> 
> It was on the example with cordova, not capacitor... but the portion of code is the same

Maybe @CSantosM remembers why this file as been removed :) 
Do we need this adapter, or not?

**Comment by CSantosM** [comment]
The doc and ionic tutorials have been updated on [openvidu-tutorials](https://github.com/OpenVidu/openvidu-tutorials) master branch.
