### ISSUE TITLE
Doc outdated (openvidu-ipcameras)

### ISSUE THREAD

**Issue by AlessandroMartinelli** [OpenVidu/openvidu.io-docs#54]
In the doc article [openvidu-ipcameras](https://docs.openvidu.io/en/stable/tutorials/openvidu-ipcameras/), section [2) Subscribe to the IP cameras](https://docs.openvidu.io/en/stable/tutorials/openvidu-ipcameras/#2-subscribe-to-the-ip-cameras) starts with a snippet of code with some non-working RTSP streams (VLC cannot play them). 

In fact, in the github project, these lines of code are replaced with the following, containing working mjpeg streams:
`	static Map<String, String> IP_CAMERAS = new HashMap<String, String>() {
		{
		 	put("Amsterdam", "http://92.110.185.114:8080/mjpg/video.mjpg");
		 	put("Czech Republic", "http://185.137.146.14:80/mjpg/video.mjpg");
			put("Japan bridge", "http://211.132.61.124:80/mjpg/video.mjpg");
		}
	};
`

Thus the doc should be updated, here.

**Comment by pabloFuente** [comment]
Already fixed with 656f7bc23d16604ca4c0dcb59e7bc57b59e6f187
