### ISSUE TITLE
ebs size 100?

### ISSUE THREAD

**Issue by rush86999** [OpenVidu/openvidu.io-docs#6]
why is the ebs size 100 gb in the aws cloud formation template? can I copy the template and make the size smaller especially if I m not going to be recording videos? Is there a minimum recommended size/

**Comment by micaelgallego** [comment]
You can change disk size if you want.

**Comment by rush86999** [comment]
is there a recommended size? What variables need to be considered when making this decision?

**Comment by micaelgallego** [comment]
If you are not going to record videos, the disk size have to be able to install OpenVidu software and ubuntu operating system. You will have to test yourself, but possible 10Gb or less should be sufficient.
